### ISSUE TITLE
Real World Data?

### ISSUE THREAD

**Issue by RichardShea** [meowoodie/Neural-Spectral-Marked-Point-Processes#1]
Hi,

Do you have the real world data examples?

Thank you,

-Richard

**Comment by meowoodie** [comment]
Hi, 

Unfortunately, some of the real world data are not publicly available. You may find the earthquake data at https://ncedc.org/. Hope this could be of some help. 

Thank you for your interest. 

Best, 
Woody

**Comment by meowoodie** [comment]
I will also release the synthetic data later in this repo.

**Comment by meowoodie** [comment]
Please find the synthetic data we used in the repo.

**Comment by RichardShea** [comment]
Hi, 

Which of these files can replicate Figures 3,4,5, and 6?

Thank you,

-Richard
