### ISSUE TITLE
.pth files?

### ISSUE THREAD

**Issue by RichardShea** [meowoodie/Neural-Spectral-Marked-Point-Processes#2]
Hi,

Do you have the .pth files that are needed for the nsmpp.ipynb file to run?

Thank you,

-Richard

**Comment by MhYao2014** [comment]
> Hi,
> 
> Do you have the .pth files that are needed for the nsmpp.ipynb file to run?
> 
> Thank you,
> 
> -Richard

No need to use "google.colab" and pre-trained ".pth" file. target models are initialized randomly. init model will fit this random target model.
